config/routes.rb
Flow::Application.routes.draw do
  
  get  '/chatroom' => 'chats#room', :as => :chat
  post '/new_message' => 'chats#new_message', :as => :new_message

  devise_for :users

  match "/users/check_username", to: "users#check_username"
  match "/users/check_email", to: "users#check_email"

  resources :users do
    member do
      get :followings
      get :followers
      post :moreposts
      post :morefollowers
      post :morefollowings
    end

    collection do 
      post :moreusers
      get :search
      post :update_activity
      post :update_last_chat_time
    end
  end

  resources :microposts, only:[:create,:destroy] do
    member do
      get :repost
    end
    resources :comments
  end
  resources :micropost_images, only: :create
  resources :connections, only:[:create,:destroy]

  root :to => 'static#home'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :username, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  VALID_USER_NAME=/\A[a-zA-Z0-9\-\. ]+\z/
  validates :username, presence: true, length: {minimum: 6}, format: {with: VALID_USER_NAME}


  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :connections, foreign_key: :follower_id, dependent: :destroy
  has_many :back_connections, foreign_key: :following_id, class_name:'Connection',dependent: :destroy
  has_many :followings, through: :connections, source: :following
  has_many :followers, through: :back_connections, source: :follower
  has_many :incoming_messages, foreign_key: :recipient_id, class_name:'Message', dependent: :destroy
  has_many :outgoing_messages, foreign_key: :sender_id, class_name:'Message', dependent: :destroy

  def feeds(options={offset:0, limit:20})
    following_ids = "select following_id from connections where follower_id = #{self.id}"
    @feeds=Micropost.where("user_id = #{self.id} or user_id in (#{following_ids})").limit(options[:limit]).offset(options[:offset])
  end

  def following?(user)
    self.connections.find_by_following_id(user.id)
  end

  def friends
    self.followings & self.followers
  end

  def to_param
    username
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except:[:check_username,:check_email]

  def index
    @users = User.limit(PAGE_LIMIT)
    @offset = PAGE_LIMIT+1 #for the more button
    if User.count< @offset
      @offset = -1 # no more microposts
    end 
  end

  def followings
    @person = User.find_by_username(params[:id])
    if @person 
      @users = @person.followings.limit(PAGE_LIMIT)
      @offset = PAGE_LIMIT+1 #for the more button
      if @person.followings.count< @offset
        @offset = -1 # no more microposts
      end 
    else
      redirect_to root_path, error:"the user #{params[:id].gsub('_',' ')} does not exist." 
    end
  end

  def followers
    @person = User.find_by_username(params[:id])
    if @person
      @users = @person.followers.limit(PAGE_LIMIT)
      @offset = PAGE_LIMIT+1 #for the more button
      if @person.followers.count< @offset
        @offset = -1 # no more microposts
      end 
    else
      redirect_to root_path, error:"the user #{params[:id].gsub('_',' ')} does not exist." 
    end
  end

  def moreusers
    @users = User.limit(PAGE_LIMIT).offset(params[:offset]) #grab all microposts
    @offset = params[:offset].to_i + PAGE_LIMIT #for the more button
    if User.count< @offset
      @offset = -1 # no more microposts
    end 

    respond_to do |format|
      format.js { render 'users/moreusers' }
    end
  end

  def morefollowers
    @user = User.find_by_username(params[:id])
    @users = @user.followers.limit(PAGE_LIMIT).offset(params[:offset]) #grab all microposts
    @offset = params[:offset].to_i + PAGE_LIMIT #for the more button
    if @user.followers.count< @offset
      @offset = -1 # no more microposts
    end 

    respond_to do |format|
      format.js { render 'users/moreusers' }
    end
  end

  def morefollowings
    @user = User.find_by_username(params[:id])
    @users = @user.followings.limit(PAGE_LIMIT).offset(params[:offset]) #grab all microposts
    @offset = params[:offset].to_i + PAGE_LIMIT #for the more button
    if @user.followings.count< @offset
      @offset = -1 # no more microposts
    end 

    respond_to do |format|
      format.js { render 'users/moreusers' }
    end
  end

  def show
    #named id
    @user = User.find_by_username(params[:id])
    @microposts = @user.microposts.limit(PAGE_LIMIT) #grab all microposts
    @offset = PAGE_LIMIT+1 #for the more button
    if @user.microposts.count< @offset
      @offset = -1 # no more microposts
    end 
  end

  def moreposts
    @user = User.find_by_username(params[:id])
    @offset = params[:offset].to_i + PAGE_LIMIT #for the more button
    if params[:category] =='feeds' #feeds or microposts
      @microposts = @user.feeds(limit:PAGE_LIMIT,offset:params[:offset])
      if FEEDS_LIMIT< @offset
        @offset = -1 # no more microposts
      end
    else
      @microposts = @user.send(params[:category]).limit(PAGE_LIMIT).offset(params[:offset])
      if @user.send(params[:category]).count< @offset
        @offset = -1 # no more microposts
      end 
    end

    respond_to do |format|
      format.js { render 'users/moreposts' }
    end
  end

  def check_username
    @user = User.find_by_username(params[:user][:username])
    if @user
      user_available=false
    else
      user_available=true
    end
    respond_to do |format|
      format.json {  render :json => user_available }
    end
  end

  def check_email
    @user = User.find_by_email(params[:user][:email])
    if @user
      user_available=false
    else
      user_available=true
    end
    respond_to do |format|
      format.json {  render :json => user_available }
    end
  end

  def search
    @usernames=User.where("username like ?","%#{params[:query]}%").select('username').map(&:username)
    #@usernames = User.find(:all,:select=>'username').map(&:username)
    respond_to do |format|
      format.json{
        render :json => @usernames.to_json
      }
    end
  end

  def update_activity
    if user_signed_in?
      current_user.update_attribute(:last_activity_time,Time.new)
    end
  end

  def update_last_chat_time
    if user_signed_in?
      current_user.update_attribute(:last_chat_time,Time.new)
    end
  end
	
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options={size:50})
    gravatar_id=Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url="http://www.gravatar.com/avatar/#{gravatar_id}.png?size=#{options[:size]}"
    image_tag(gravatar_url, alt: user.username, class:'gravatar img-rounded',
    	title: 'change profile image through gravatar.com')
  end

  def delete_micropost_privilege?(micropost)
    current_user.admin === true || current_user === micropost.user  
  end


	def delete_comment_privilege?(comment)
    current_user.admin? || current_user === comment.micropost.user ||	current_user === comment.user
  end

end

app/views/users/_connected_users_modal.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h2 id="connectedUsersModalLabel"><%= modal_header %></h2>
</div>
<div class="modal-body">
	<%= render users %>
</div>
<div class="modal-footer">
  <button class="btn btn-inverse micropost_form_btns" data-dismiss="modal" aria-hidden="true">Close</button>
</div>

app/views/users/_connection_action_form.html.erb
<div class="connection_action">	
	<% if current_user.following?(user) %>
		<%= render 'connections/unfollow_form', user:user %>
	<% else %>
		<%= render 'connections/follow_form', user:user %>
	<% end %>
</div>

app/views/users/_horizontal_profile.html.erb
<div class="span2">
		<%= gravatar_for(user, size:160) %>
</div>

<div class="span4">
	<b><%= link_to user.username, user, {class:'micropost_user_link',style:"font-size: 150%"}%></b><br>
	<%= link_to  ("<span class='user_followings_count'>"+pluralize(user.followings.count,'following')+"</span>").html_safe, followings_user_path(user) %><br>
	<%= link_to  ("<span class='user_followers_count'>"+pluralize(user.followers.count,'follower')+"</span>").html_safe, followers_user_path(user) %><br>
	 <%= link_to ("<span class='user_microposts_count'>"+pluralize(user.microposts.count,'micropost')+"</span>").html_safe , user_path(user) %>
</div>

app/views/users/_icon.html.erb
<div class="span1">
<%= link_to gravatar_for(user, size:75),'#', class:'user_popover', "data-content"=> "#{ render 'users/icon_popover', user:user }" %><br>
</div>

app/views/users/_icon_popover.html.erb
<div class="span4">
	<b><%= link_to user.username, user, {class:'micropost_user_link',style:"font-size: 120%"}%></b><br>
	<%= link_to  ("<span class='user_followings_count'>"+pluralize(user.followings.count,'following')+"</span>").html_safe, followings_user_path(user) %><br>
	<%= link_to  ("<span class='user_followers_count'>"+pluralize(user.followers.count,'follower')+"</span>").html_safe, followers_user_path(user) %><br>
	 <%= link_to ("<span class='user_microposts_count'>"+pluralize(user.microposts.count,'micropost')+"</span>").html_safe , user_path(user) %>
</div>

<% unless current_user === user %>
<div style="clear:both; padding-top:5px;" class="connection_action">			
		<% if current_user.following?(user) %>
			<%= render 'connections/unfollow_form', user:user %>
		<% else %>
			<%= render 'connections/follow_form', user:user %>
		<% end %>
</div>
<% end %>

app/views/users/_microposts_main.html.erb
<div id="microposts_content">
<%= render @microposts %>
</div>

<% unless @offset == -1 %> 
	<div class='row' id="more_post_row">
		<div class='span2 center'>
			<!-- the user object is passed in -->
			<%= form_tag(moreposts_user_path(user),remote:true) do %>
				<div id="more_post_offset">
				<%= hidden_field_tag 'offset', @offset %>
				</div>
				<!-- the category is passed in to distinguish feeds and microposts-->
				<%= hidden_field_tag 'category', category %>
				<%= submit_tag('More Micropsots ...', class:'btn btn-large btn-primary') %>
			<% end %>
		</div>
	</div>
<% end %>

<!-- repost modal -->
<div id='repostModal' class='modal hide fade' tabindex="-1" role='dialog'>
</div>

app/views/users/_user.html.erb
<div class="row">
<div class="span3">
	<div class="row">
		<div class="span1">
			<%= gravatar_for(user, size:100) %>

		</div>
		<div class="span2">
				<%= render 'users/user_profile', user:user %>
		</div>
	</div>
	<div class="row">
		<div class="span3">
		<% unless current_user === user %>
			<div style="clear:both; padding-top:5px;">		
				<%= render 'users/connection_action_form', user:user %>
			</div>
		<% end %>
		</div>
	</div>
</div>

<div class="span9">
	<p><i>latest micropost:</i> <br>
		<div class="well">
		<% if user.microposts.any? %>
			<%= render 'microposts/micropost_content', micropost:user.microposts.first %>
		<% else %>
			<%= user.username %> has not published any micropost yet.
		<% end %>
		</div>
	</p>
</div>
</div>
<hr>

app/views/users/_vertical_profile.html.erb
<div class="span2">
<%= gravatar_for(user, size:120) %>
<br>
<p style="padding-top:5px;">
<b style="font-size: 150%;"><%= link_to user.username, user, {class:'micropost_user_link'}%></b><br>
<div class="row">
<small class="span3" style="margin-top:-10px;">
	<%= link_to  ("<span class='user_followings_count'>"+pluralize(user.followings.count,'following')+"</span>").html_safe, followings_user_path(user) %> | 
	<%= link_to  ("<span class='user_followers_count'>"+pluralize(user.followers.count,'follower')+"</span>").html_safe , followers_user_path(user)%><br>
	 <%= link_to ("<span class='user_microposts_count'>"+pluralize(user.microposts.count,'micropost')+"</span>").html_safe , user_path(user) %>

</small>
</div>
</p>
</div>

app/views/users/followers.html.erb
<h3><%=@person.username%> has <span class="user_followers_count"><%= pluralize(@person.followers.count,'follower')%></span></h3>

<div id='users_content'>
<%= render @users %>
</div>

<% unless @offset == -1 %> 
	<div class='row' id="more_user_row">
		<div class='span2 center'>
			<%= form_tag({controller:"users",action:"morefollowers"},method:"post",remote:true) do %>
				<div id="more_user_offset">
				<%= hidden_field_tag 'offset', @offset %>
				</div>
				<%= hidden_field_tag 'id', @person.username %>
				<%= submit_tag('More ...', class:'btn btn-large btn-primary') %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/users/followings.html.erb
<h3><%=@person.username%> has <span class="user_followings_count"><%= pluralize(@person.followings.count,'following')%></span></h3>

<div id='users_content'>
<%= render @users %>
</div>

<% unless @offset == -1 %> 
	<div class='row' id="more_user_row">
		<div class='span2 center'>
			<%= form_tag({controller:"users",action:"morefollowings"},method:"post",remote:true) do %>
				<div id="more_user_offset">
				<%= hidden_field_tag 'offset', @offset %>
				</div>
				<%= hidden_field_tag 'id', @person.username %>
				<%= submit_tag('More ...', class:'btn btn-large btn-primary') %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/users/index.html.erb
<h2>All Users</h2>

<div id='users_content'>
<%= render @users %>
</div>

<% unless @offset == -1 %> 
	<div class='row' id="more_user_row">
		<div class='span2 center'>
			<%= form_tag({controller:"users",action:"moreusers"},method:"post",remote:true) do %>
				<div id="more_user_offset">
				<%= hidden_field_tag 'offset', @offset %>
				</div>
				<%= submit_tag('More ...', class:'btn btn-large btn-primary') %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/users/moreposts.js.erb
$("#microposts_content").append("<%= escape_javascript(render @microposts)%>");

$('.user_popover').popover({
  offset: 10,
  trigger: 'manual',
  animate: true,
  html: true,
  placement: 'right',
  template: '<div class="popover" onmouseover="clearTimeout(timeoutObj);$(this).mouseleave(function() {$(this).hide(); });"><div class="arrow"></div><div class="popover-inner"><h3 class="popover-title"></h3><div class="popover-content"><p></p></div></div></div>'

}).click(function(e) {
    e.preventDefault() ;
}).mouseenter(function(e) {
    $(this).popover('show');
}).mouseleave(function(e) {
  var ref = $(this);
  timeoutObj = setTimeout(function(){
      ref.popover('hide');
  }, 50)});
  

var offset = parseInt("<%= @offset %>");
if (offset == -1 ){
	$('#more_post_row').hide();
} else {
$("#more_post_offset").html("<%= escape_javascript(hidden_field_tag 'offset', @offset ) %>")
$("#more_post_row form :submit").val("More Micropsots ...");
}

app/views/users/show.html.erb
<div class="row">
	<% if @user == current_user %>
		<!-- span2 -->
		<%= render 'users/vertical_profile', user:@user %>
		<!-- add micropost form if is current_user, span10 -->
		<%= render 'microposts/form' %>
	<% else %>
		<!-- span 4 -->
		<%= render 'users/horizontal_profile', user:@user %>
		<!-- Add the follow/unfollow button if is other user-->
		<div class="pull-right">
			<%= render 'users/connection_action_form', user:@user%>
		</div>
	<% end %>
</div>

<hr>

<% if @user == current_user %>
	<h3>All your microposts</h3>
<% else %>
	<h3>All <%= @user.username %>'s microposts</h3>
<% end %>
<br>

<!-- A partial shared by home page and show page, all instance variables are passed in -->
<%= render 'users/microposts_main', category:'microposts', user:@user %>

app/views/users/update_activity.js.erb
// add new message notification
<% if unread_messages(current_user) && unread_messages(current_user).size > 0 %>
	$('#chat_status').text("Chat(<%= unread_messages(current_user).size %>)");
<% end %>

<% current_user.friends.each do |friend| %>
	<% if friend.last_activity_time && (friend.last_activity_time > 1.minutes.ago) %>
  	$("#friend<%=friend.id%>_online_status").html("<strong>online</strong>")      
  <% else %>
    $("#friend<%=friend.id%>_online_status").html("offline")
	<% end %>
<% end %>