config/routes.rb
Flow::Application.routes.draw do
  
  get  '/chatroom' => 'chats#room', :as => :chat
  post '/new_message' => 'chats#new_message', :as => :new_message

  devise_for :users

  match "/users/check_username", to: "users#check_username"
  match "/users/check_email", to: "users#check_email"

  resources :users do
    member do
      get :followings
      get :followers
      post :moreposts
      post :morefollowers
      post :morefollowings
    end

    collection do 
      post :moreusers
      get :search
      post :update_activity
      post :update_last_chat_time
    end
  end

  resources :microposts, only:[:create,:destroy] do
    member do
      get :repost
    end
    resources :comments
  end
  resources :micropost_images, only: :create
  resources :connections, only:[:create,:destroy]

  root :to => 'static#home'

  

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :body, :body_html, :original_post_id

  belongs_to :user

  has_many :micropost_images, dependent: :destroy
  has_many :comments, dependent: :destroy

  # self join relationship for repost
  has_many :reposts, class_name: 'Micropost', foreign_key: :original_post_id
  belongs_to :original_post, class_name: 'Micropost'

  # accepts_nested_attributes_for :micropost_images, allow_destroy: true, 
  #   :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

  validates :body, presence: true, length: {maximum: 140} 

  auto_html_for :body do
    html_escape
    sized_image
    youtube(:width => 400, :height => 250)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

  before_validation do |micropost|
    unless micropost.body
      micropost.body='Repost'
    end
  end

  default_scope order: "microposts.created_at DESC"
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	
	before_filter :authenticate_user!

	before_filter :destroy_privilege, only: :destroy

	def create
		@micropost=Micropost.new(params[:micropost])
		@micropost.user= current_user

		image_ids=params[:image_ids]

		respond_to do |format|
			if @micropost.save
				if image_ids
					image_ids.each do |image_id|
						MicropostImage.find(image_id).update_attribute(:micropost_id,@micropost.id)
					end
				end
				format.html { redirect_to root_path, notice: 'New micropost published' }
			else
				flash[:error]=@micropost.errors.full_messages.join(', ').html_safe
				format.html { redirect_to root_path }
			end
		end
	end

	def repost
		@micropost=Micropost.find(params[:id])
	end


	def destroy
		#@micropost=Micropost.find(params[:id])
		@micropost.delete
		redirect_to user_path(@micropost.user), notice: 'Post deleted'
	end
	
	private

	def destroy_privilege
		@micropost = Micropost.find(params[:micropost_id])
		redirect_to root_path, error: "Only micropost owner or comment owner can delete comment" unless current_user === @micropost.user or current_user.admin?
	end

end

app/helpers/microposts_helper.rb
module MicropostsHelper

	def original_post_content(micropost)
		str="<div class='well' style='font-size:90%;'>"
		str+= '@'
		str+= link_to(micropost.user.username, micropost.user)
		str += '<br>'
		str += micropost.body_html

		if micropost.original_post
			str += original_post_content(micropost.original_post)
		end	

		str += "<div>"
		str += "<small style='color: gray;'>"
		str += "<i>Created at: #{time_ago_in_words(micropost.created_at)}</i>"
		str += "</small>"
		str += "<span class='pull-right' id='micropost#{micropost.id}_options'>"
		str += link_to("Reposts(#{micropost.reposts.count})", repost_micropost_path(micropost.id), remote:true, class:"micropost_repost_revealer")
		str += "&nbsp;|&nbsp;"
		str += link_to("Comments(#{micropost.comments.count})", micropost_comments_path(micropost.id), remote:true, class:"micropost_comment_revealer")
		if delete_micropost_privilege?(micropost)
			str += "&nbsp;|&nbsp;"
			str += link_to("delete", micropost, :method => :delete, :confirm => "Are you sure to delete the post?", class:'btn btn-small')
		end 
		str += "</span>"
		str += "</div>"

		str += "<div class='micropost_comments' style='margin-top: 10px; display:none;'>"
		str += "<div id='micropost_comments#{micropost.id}_form'>"
		str += render('comments/form',micropost:micropost)
		str += '</div>'
		str += "<div id='micropost_comments#{micropost.id}_info' style='display:none;'></div>"
		str += "<div class='show_micropost_comments#{micropost.id}'></div>"
		str += "</div></div>"
		
		raw(str)
	end


	def micropost_content(micropost, options={originial_post:false})
		#remove the <p></p> tags around the content
		content=micropost.body_html.gsub(/<p>/,'').gsub(/<\/p>/,'') 
		if micropost.original_post
			micropost.original_post.reposts.each do |repost|
				if repost.created_at < micropost.created_at
					content+= ' //'
					content+= link_to('@'+repost.user.username, repost.user)
					content+= ': '
					content+= strip_tags(repost.body_html) 
				end
			end
		end

		content_tag :div, class:"micropost_content" do
			str = "<div>"
			if options[:original_post]
				str+= '@'
				str+= link_to(micropost.user.username, micropost.user)
				str+= '<br>'
			end
			str += content
			if micropost.micropost_images.any?
				image_index=0
				str += "<ul class='thumbnails'>"
				micropost.micropost_images.each do |image|
					image_index+=1
					str += "<li class='span2'>"
					class_name = "#{current_user.username}_micropost#{micropost.id}_images thumbnail"
					str += link_to(image_tag(image.image_url), image.image_url, class: class_name) 
					str += "</li>"
					if image_index%5==0
						str += "</ul>"
						str += "<ul class='thumbnails'>"
					end
				end
				str += "</ul>"
			end
			str += "</div>"

			if micropost.original_post
				str += "<div class='well' style='font-size:95%;'>"
				str += micropost_content(micropost.original_post,{original_post:true})
				str += "</div>"
			end	

			str += "<div>"
			str += "<small style='color: gray;'>"
			str += "<i>Created at: #{time_ago_in_words(micropost.created_at)}</i>"
			str += "</small>"
			str += "<span class='pull-right' id='micropost#{micropost.id}_options'>"
			str += link_to("Reposts(#{micropost.reposts.count})", repost_micropost_path(micropost.id), remote:true, class:"micropost_repost_revealer")
			str += "&nbsp;|&nbsp;"
			str += link_to("Comments(#{micropost.comments.count})", micropost_comments_path(micropost.id), remote:true, class:"micropost_comment_revealer")
			if delete_micropost_privilege?(micropost)
				str += "&nbsp;|&nbsp;"
				str += link_to("delete", micropost, :method => :delete, :confirm => "Are you sure to delete the post?", class:'btn btn-small')
			end 
			str += "</span></div>"

			str += "<div class='micropost_comments' style='margin-top: 10px; display:none;'>"
			str += "<div id='micropost_comments#{micropost.id}_form'>"
			str += render('comments/form',micropost:micropost)
			str += '</div>'
			str += "<div id='micropost_comments#{micropost.id}_info' style='display:none;'></div>"
			str += "<div class='show_micropost_comments#{micropost.id}'></div>"
			str += "</div>"

			raw(str)
		end
	end
end

app/views/microposts/_form.html.erb
<div class="span10">
	<% @micropost=Micropost.new %>


	<%= form_for @micropost, html:{id:'new_micropost_form'} do |f| %>
		<%= f.text_area(:body,rows:5,style:'width:98.1%',placeholder:'What is on your mind?', required:'required',title:'Tip: you can paste links for images and youtube videos directly here') %>
		<br>
		<div class="pull-right">

		 <a href="#addImageModal" class="btn btn-info micropost_form_btns" role="button" data-toggle="modal" id="add_image">Add Images</a>
		 <input type='hidden' name='submittingImage' value='no' />

		<%= f.submit '  Publish Post  ',class:'btn btn-primary micropost_form_btns', disabled:'disabled' %>
		</div>
	<% end %>

	<div id='addImageModal' class="modal hide fade" tabindex="-1" role="dialog">
		<div class="modal-header">
    	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    	<h3 id="addImageModalLabel">Select all image(s) here ...</h3>
  	</div>

  	<div class="modal-body">
			<%= s3_uploader_form post: micropost_images_url, as: "micropost_image[image_url]", id: "imageS3Uploader" do %>
		  	<%= file_field_tag :file, multiple: true %>
			<% end %>

			<script id="template-upload" type="text/x-tmpl">
				<div class="upload">
					{%=o.name%}
					 <div class="progress"><div class="bar" style="width: 0%"></div></div>
				</div>
			</script>
		</div>
		<div class="modal-footer">
			<small>Wait for adding images finished before publishing post</small>&nbsp;
			<button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Finish</button>
		</div>
	</div>
</div>

app/views/microposts/_image_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3>Add images to post</h3>
</div>

<div class="modal-body">
<% index=0 %>
<div class="row">
  <div class="span3">
  <h4>From local storage</h4>
  </div>
  <div class="span3">
  <h4>From internet (Paste image url)</h4>
  </div>
</div>

<%= f.fields_for :micropost_images do |micropost_image_form| %>
  <% if index<6 %>
    <% if index%2 == 0 %>
      <div class="row">
        <div class="span3"> 
          <%= micropost_image_form.file_field :image%>
        </div>
    <% else %>
        <div class="span3">
          <%= micropost_image_form.text_field :remote_image_url %>
        </div>
      </div>
    <% end %>
  <% else %>
    <% if index%2 == 0 %>
      <div class="row new_post_add_more_image_fields" style="display:none;">
        <div class="span3"> 
          <%= micropost_image_form.file_field :image%>
        </div>
    <% else %>
        <div class="span3">
          <%= micropost_image_form.text_field :remote_image_url %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% index+=1 %> 
<% end %>

<p>
  <button class='btn btn-info' type="button" id="new_post_add_more_image_button"><i class="icon-picture icon-white"></i> More Images ...</button>
</p>
</div>

<div class="modal-footer">
  The images will be uploaded when you publish the post&nbsp;&nbsp;&nbsp;
  <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Finish</button>
</div>

app/views/microposts/_micropost.html.erb
<div class="row">
<!-- this is span1 -->
<%= render 'users/icon', user:micropost.user %>

<div class="span11">
	<%= link_to micropost.user.username, micropost.user, {class:'micropost_user_link'}%><br>
  <%= render 'microposts/micropost_content', micropost:micropost %>
</div>

</div>

<hr>

app/views/microposts/_micropost_content.html.erb
<script>

  $(document).ready(function(){
    $("a.<%= current_user.username%>_micropost<%=micropost.id%>_images").colorbox({rel:'<%= current_user.username%>_micropost<%=micropost.id%>_images',maxWidth:"600px", });
  });
  
</script>

<%= micropost_content(micropost) %>

app/views/microposts/_repost_form.html.erb
<script>
$(document).ready(function(){

	$('#repost_form').find('textarea').bind('hastext', function () {
	  $('#repost_form').find(':submit').removeClass('disabled').attr('disabled', false);
	});
	        
	$('#repost_form').find('textarea').bind('notext', function () {
	  $('#repost_form').find(':submit').addClass('disabled').attr('disabled', true);
	});

});  
</script>

<% @repost=Micropost.new %>

<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel">Repost</h3>
</div>

<div class="modal-body">
<div class="well"><%= original_post.body_html %></div>

<%= form_for @repost, html:{id:'repost_form'} do |f| %>
	<%= f.hidden_field :original_post_id, value: original_post.id %>
	<%= f.text_area(:body,rows:5,style:'width:95%',placeholder:'What is on your mind?', required:'required') %>
	<br>
	<div class="pull-right">
	<%= f.submit '  Repost  ',class:'btn btn-primary', disabled:'disabled' %>
	</div>
<% end %>

</div>

app/views/microposts/repost.js.erb
$('#repostModal').html("<%= escape_javascript(render('microposts/repost_form',original_post:@micropost))%>");
$('#repostModal').modal('show');