config/routes.rb
Flow::Application.routes.draw do
  
  get  '/chatroom' => 'chats#room', :as => :chat
  post '/new_message' => 'chats#new_message', :as => :new_message

  devise_for :users

  match "/users/check_username", to: "users#check_username"
  match "/users/check_email", to: "users#check_email"

  resources :users do
    member do
      get :followings
      get :followers
      post :moreposts
      post :morefollowers
      post :morefollowings
    end

    collection do 
      post :moreusers
      get :search
      post :update_activity
      post :update_last_chat_time
    end
  end

  resources :microposts, only:[:create,:destroy] do
    member do
      get :repost
    end
    resources :comments
  end
  resources :micropost_images, only: :create
  resources :connections, only:[:create,:destroy]

  root :to => 'static#home'

  

end

app/views/layouts/_footer.html.erb
<div class="row footer">
  <hr>
  <div class="row">
    <div class="span12" style="text-align: center">
      <small>&copy; Ming He 2012</small>
    </div>
  </div>  
    
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container" style="width:auto;">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a href="/" class="brand"><b>Flow</b></a> 
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Chat", chat_path, id:'chat_status' %></li>
          <% if signed_in? %>   
            <li><%= link_to "All Users", users_path %></li> 
          <% end %>
        </ul>
        <form class="navbar-search pull-left">
          <input type="text" id="username_searchbox" class="search-query span2" placeholder="Search Users">
        </form>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i> <%=current_user.username%> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Change Profile Picture", 'https://en.gravatar.com', target:'_blank' %></li>
                <li><%= link_to "Edit Account", edit_user_registration_path %></li>
                <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>             
              </ul>
            </li>
          <% end %>
        </ul>
      </div>     
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	
  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
  <title><%= content_for?(:title) ? "Flow App | "+yield(:title) : "Flow App" %></title>

  <!-- Included CSS Files -->
  <%= stylesheet_link_tag    "application" %>

  <!-- Included JS Files for colorbox  -->
  <%= javascript_include_tag "header" %>
 
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/header' %>

  <div class="container">

    <!-- Flash notice-->
    <div class="row">
      <div class="span12">
        <div id="application_flash">
        <% flash.each do |key,value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        </div>
      </div>
    </div>

  <%= yield %>
  
  <%= render 'layouts/footer' %>
  
  <%= debug(params.inspect) if Rails.env.development?%>
  
  </div>

    <!-- Included JS Files  -->
  <%= javascript_include_tag "application" %>

  <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"></script>


</body>
</html>